apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    env: my-app
    owner: Eziz
spec:
  selector:
    app: my-app
  ports:
    - name: app-listener
      protocol: TCP
      port: 80
      targetPort: 80 
  type: LoadBalancer