apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-1
  labels:
    app: my-k8s-deployment-1
spec:
  replicas: 3
  selector:
    matchLabels:
      project: kgb-1
  template:
    metadata:
      labels:
        project: kgb-1
    spec:
      containers:
        - name: my-web-deployment-1
          image: adv4000/k8sphp:version1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-web-deployment-1
  labels:
    env: prod
    owner: Eziz
spec:
  selector:
    project: kgb-1
  ports:
    - name: app-listener
      protocol: TCP
      port: 80
      targetPort: 80 
  type: LoadBalancer